### ISSUE TITLE
刚启动时，第一个标签“网易”不是选中的红色

### ISSUE THREAD

**Issue by hoody4032** [HAHAKea/HACursor#2]
![bug](https://cloud.githubusercontent.com/assets/3246146/8898909/ccf5f992-33e1-11e5-88c7-c29e75cbf8ba.png)

另外，您有联系方式么？如微博，email？多谢。

**Comment by HAHAKea** [comment]
谢谢 已经改过来了

**Comment by HAHAKea** [comment]
微博 ：国锋童鞋

**Comment by hoody4032** [comment]
谢谢！
