### ISSUE TITLE
ViewController的class为什么是UINavigationController？

### ISSUE THREAD

**Issue by hoody4032** [HAHAKea/HACursor#3]
我觉得应该是UIViewController。可是如果用UIViewController，您的例子就会crash。

2015-07-27 19:16:02.860 HACursor[1416:67178] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 9223372036854775808 beyond bounds [0 .. 11]'

**Comment by HAHAKea** [comment]
这是我在storyboard里面拖的一个UINavigationController,主要是验证之前一个开发者向我提出UINavigationController下HACursor会有小间隙的问题，（你也可以看到我标题写的是测试程序），可实测的时候并没什么发现有问题，如果你确实不想要UINavigationController的话，你可以在storyboard把它删了，再拖一个UIViewController就好了。
     然后关于isGraduallyChangFont  isGraduallyChangColor 这两个属性我也修复了，实测正常。
     最后，谢谢你对HACursor提出的意见和对HACursor的关注，下一个版本将会在rootScrollView上添加一些转场动画供开发者选择。

**Comment by hoody4032** [comment]
感谢。两个问题都修正了。
