### ISSUE TITLE
请问怎么调整title之间的距离？

### ISSUE THREAD

**Issue by hoody4032** [HAHAKea/HACursor#5]
我觉得现在的title之间的距离有些大。好像没有看到有property可以调节。您能把设置title距离的参数加到property里么？

我现在是用swift语言调用您的library。您有打算开发swift版的library么？

多谢。

**Comment by HAHAKea** [comment]
HAScrollNavBar 里面有一个宏定义 “#define ItemWidth 75”  你可以将它调小一点，目前只支持每个title都一样大小，下一步准备根具title字体长度来自行计算。  
swift版我有打算写，不过没这么快。
